#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    frontend-app:
        image: frontend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://frontend-mysql:3306/frontend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=frontend-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=frontend-elasticsearch:9300
        ports:
            - 8080:8080
    frontend-mysql:
        extends:
            file: mysql.yml
            service: frontend-mysql
    # Uncomment to have Cassandra working with the gateway
    # frontend-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: frontend-cassandra
    # frontend-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: frontend-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    frontend-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: frontend-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
